dataset_name: default
dataset_path: arrow
dataset_kwargs:
  data_files:
    test: /home/lm2445/project_pi_sjf37/lm2445/PV_multiagent/benckmark/PV_benckmark/pv_arrow_dataset/pv_annotator_dataset/data-00000-of-00001.arrow
output_type: generate_until
doc_to_target: "{{answer}}"
doc_to_text: "{{query}}"
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "JSON_END"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 1024
metric_list:
  - metric: !function pv_utils.evaluate_eppc
    aggregation: !function pv_utils.evaluate_eppc_agg
    higher_is_better: true
metadata:
  version: '1.0'
task: PvExtraction_full_all
tag: Pv
test_split: test
